version: "3"
services:
  web:
    # 将 username/repo:tag 替换为您的名称和镜像详细信息
    image: charlenezell/mydemo1:part1
    deploy:
      replicas: 20
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:

# 从镜像库中拉取我们在步骤 2 中上传的镜像。

# 将该镜像的五个实例作为服务 web 运行，并将每个实例限制为最多使用 10% 的 CPU（在所有核心中）以及 50MB RAM。

# 如果某个容器发生故障，立即重启容器。

# 将主机上的端口 80 映射到 web 的端口 80。

# 指示 web 容器通过负载均衡的网络 webnet 共享端口 80。（在内部，容器自身将在临时端口发布到 web 的端口 80。）

# 使用默认设置定义 webnet 网络（此为负载均衡的 overlay 网络）。